---
title: "Trust Scores in R"
author: "Sarah Gillespie"
output: html_document
---

## Before we begin...

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(eval = FALSE)

```

```{r libraries}

# Load the R libraries
library(palmerpenguins) # bring in data about penguin species
library(dplyr) # tools for data wrangling in R
library(reticulate) # provides a comprehensive set of tools for interoperability between Python and R.

```

```{r}
# configure python
reticulate::py_config() # Double check that reticulate is actually using your new conda env.
reticulate::py_install("sklearn", pip = TRUE) # force install with pip. sklearn wasn't coming up via anaconda.
reticulate::py_install("matplotlib")
reticulate::py_install("keras")
reticulate::py_install("pandas")

# setting up the Python environment and bringing in the required Python packages is important.
# It will probably take a little while so be patient and try to avoid accidentally running
# this chunk of code.

# common trouble shooting:
# if you're missing a package then try adding its name in an additional line of py_install
# if py_install isn't working then try adding the pip = TRUE argument to try installing
# the library through pip rather than anaconda
```

```{python}
# import python packages
# this brings in packages that you installed onto your computer into the R 
# environment to be able to adequately run Python within R Studio.

import numpy as np
import trustscore # you need to have trustscore.py in the same folder as this .Rmd file to import it
import trustscore_evaluation  # you need to have trustscore_evaluation.py in the same folder as this .Rmd file to import it
import numpy as np
import matplotlib.pyplot as plt
import keras
import pandas as pd

# heads up! there might be some scary errors about "dlerror: cudart64_110.dll not found".
# It's just a warning and you can ignore it.

```

```{r}

# data wrangling
# remove all lines with NaN and N/A so the model can be fit on the data
penguins_df <- penguins %>%
    dplyr::filter(complete.cases(.)) 

# choose the data columns to use in the model
penguins_data <- penguins_df %>%
  dplyr::select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)

# prediction target: species
penguins_target <- penguins_df %>%
  dplyr::select(species)

```


```{python}

# Import penguins from R into Python
penguins_data = r.penguins_data

penguins_target = r.penguins_target

# encode each penguin species to be a number.
# purpose: make it easier for the model to assign a species and a trust score to the species prediction.
dictionary = {}
current_index = 0

def encode(value):
    if value in dictionary:
      return dictionary[value]
    else:
      global current_index
      
      new_index = current_index
      dictionary[value] = new_index
      current_index = current_index + 1
      
      return new_index

X_penguins = penguins_data

y_penguins = list(map(encode, penguins_target.values.ravel()))
# at this point y_penguins is a list. We will need to make it a numpy array later.

print(dictionary) # dictionary with each penguin species connected to its assigned number
```

```{python}
# bring in  Python machine learning library scikit-learn, abbreviated as sklearn

# select the specifc model
from sklearn.linear_model import LogisticRegression

# assign your chosen model to the general model variable
model = LogisticRegression()

```

```{python}

# implement the model
model.fit(X_penguins, y_penguins)

# generate predictions
y_pred = model.predict(X_penguins)

# You may get a "failed to converge" and "max number of interations reached" warning.
# this is more about the data not fitting well to the assigned model rather than a tech issue.
# sarah add mire details about what this means from an ML perspective.


```

```{python}
# Initialize trust score from the trustscore.py file
trust_model = trustscore.TrustScore()

# have the x and y inputs be converted to numpy arrays
X_penguins = np.array(X_penguins)
y_penguins = np.array(y_penguins)

# fit the trust scores to the model
trust_model.fit(X_penguins, y_penguins)

```


```{python}
# Compute the trusts score
# provide the model with (unlabeled) testing examples and (hard) model predictions.
trust_score = trust_model.get_score(X_penguins, y_pred)

print(trust_score) # prints the trust scores for each point in the inputted data set

```

```{r}
# use this code to trace back the last error. Errors are solved now, so this is not needed.
# py_last_error()
```


### Resources
Trust Scores functions from the Google Scholars paper: https://github.com/google/TrustScore
To Trust Or Not To Trust A Classifier paper by Heinrich Jiang, Been Kim, Melody Y. Guan, Maya Gupta: https://arxiv.org/abs/1805.11783
Reticulate documentation: https://rstudio.github.io/reticulate/

